### ISSUE TITLE
Compile issue [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [wipu/sidex-vcv#1]
g++ -std=c++11 -Wsuggest-override  -fPIC -I../../../include -I../../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/SidEx.cpp.o src/SidEx.cpp
src/SidEx.cpp:9:8: error: 'void MidiOutput::onMessage(uint8_t*, size_t)' marked 'override', but does not override
    9 |   void onMessage(uint8_t *bytes, size_t size) override {
      |        ^~~~~~~~~
src/SidEx.cpp: In member function 'void MidiOutput::onMessage(uint8_t*, size_t)':
src/SidEx.cpp:10:42: error: no matching function for call to 'MidiOutput::sendMessage(uint8_t*&, size_t&)'
   10 |     midi::Output::sendMessage(bytes, size);
      |                                          ^
In file included from ../../../include/rack.hpp:15,
                 from src/plugin.hpp:2,
                 from src/SidEx.cpp:1:
../../../include/midi.hpp:186:7: note: candidate: 'void rack::midi::Output::sendMessage(rack::midi::Message)'
  186 |  void sendMessage(Message message);
      |       ^~~~~~~~~~~
../../../include/midi.hpp:186:7: note:   candidate expects 1 argument, 2 provided
make: *** [../../../compile.mk:68: build/src/SidEx.cpp.o] Error 1

**Comment by wipu** [comment]
The output looks like you are trying to compile SidEx with the official Rack. At the moment my patched Rack is required, since the official branch doesn't support longer (sysex) midi messages.

You may want to try the compilation script that comes with SidEx. I haven't tested it in any of the unix environments of Windows (msys, cygwin, ...)

I just created a pull request for my Rack patch https://github.com/VCVRack/Rack/pull/1713

If you want to help speed things up, you may want to comment the pull request or one of the related Rack issues.

**Comment by wipu** [comment]
My Rack PR was rejected so I don't know when SidEx can be used with official Rack. @SteveRussell33 is there any other way I can help?

**Comment by SteveRussell33** [comment]
Having read the comments concerning this, I think in the mean time I will build another custom Rack EXE with your patch to test; I have a couple of other PR's added to it so this is not a problem for me as I pretty much build everything for Rack myself anyway.

I see that Andrew has indicated https://github.com/VCVRack/Rack/issues/1433#issuecomment-559625345 that this will be possible (i.e. PR not needed) in Rack v2 API. So for those that want this now, have to build Rack + PR themselves or wait for v2 to be released.

I'll close this for now and reopen when v2 gets closer and go from there.
